# embed_webui_resources.cmake
# 将 WebUI/ 目录下的 .html / .js / .css 文件编译为 C++ constexpr 字节数组，
# 生成 webui_resources.h 供 WebUIServer 在编译时内联使用。
#
# constexpr char[] 数据定义与 kResources 的 std::string_view 数组分离定义，
# 以符合 C++20 语法要求。
#
# 用法:
#   cmake -DINPUT_DIR=path/to/WebUI -DOUTPUT_FILE=path/to/webui_resources.h -P this_script.cmake

if(NOT INPUT_DIR OR NOT OUTPUT_FILE)
    message(FATAL_ERROR "INPUT_DIR and OUTPUT_FILE are required")
endif()

# 收集需要嵌入的资源文件
file(GLOB RESOURCE_FILES
    "${INPUT_DIR}/*.html"
    "${INPUT_DIR}/*.js"
    "${INPUT_DIR}/*.css"
)

list(SORT RESOURCE_FILES)

if(NOT RESOURCE_FILES)
    file(GLOB ALL_FILES "${INPUT_DIR}/*")
    message(FATAL_ERROR "No .html / .js / .css files found in ${INPUT_DIR}. "
                        "Directory contents: ${ALL_FILES}")
endif()

# --- 生成头文件 ---
set(HEADER
"// Auto-generated by embed_webui_resources.cmake — do not edit
#pragma once

#include <cstddef>
#include <string_view>

namespace tianyan::webui::embedded {

struct Resource {
    std::string_view path;
    std::string_view data;
};

"
)

# 收集 kResources 条目
set(RESOURCE_ENTRIES "")

foreach(FILE_PATH ${RESOURCE_FILES})
    get_filename_component(FILE_NAME "${FILE_PATH}" NAME)

    # 将文件名转为合法 C++ 标识符
    string(REGEX REPLACE "[^a-zA-Z0-9]" "_" DATA_NAME "${FILE_NAME}")
    set(DATA_VAR "kData_${DATA_NAME}")

    # 读取文件内容为十六进制
    file(READ "${FILE_PATH}" FILE_HEX HEX)
    string(LENGTH "${FILE_HEX}" HEX_LEN)

    # 没有内容则跳过
    if(HEX_LEN EQUAL 0)
        continue()
    endif()

    # 每 20 个字节一行（40 个 hex 字符 = 20 字节）
    set(BYTES_PER_LINE 20)
    math(EXPR LINE_CHAR_COUNT "${BYTES_PER_LINE} * 2")

    string(APPEND HEADER "// ${FILE_NAME}\n")
    string(APPEND HEADER "inline constexpr unsigned char ${DATA_VAR}[] = {\n")

    set(REMAINING "${FILE_HEX}")
    while(TRUE)
        string(LENGTH "${REMAINING}" REMAINING_LEN)
        if(REMAINING_LEN EQUAL 0)
            break()
        endif()

        # 取 LINE_CHAR_COUNT 个字符（一组）
        string(SUBSTRING "${REMAINING}" 0 ${LINE_CHAR_COUNT} LINE_HEX)
        string(REGEX REPLACE "(..)" "0x\\1, " LINE_BYTES "${LINE_HEX}")
        # 去掉末尾 ", "
        string(REGEX REPLACE ", $" "" LINE_BYTES "${LINE_BYTES}")

        string(APPEND HEADER "    ${LINE_BYTES},\n")

        # 剩余部分
        math(EXPR REMAINING_LEN "${REMAINING_LEN} - ${LINE_CHAR_COUNT}")
        if(REMAINING_LEN GREATER 0)
            string(SUBSTRING "${REMAINING}" ${LINE_CHAR_COUNT} ${REMAINING_LEN} REMAINING)
        else()
            break()
        endif()
    endwhile()

    string(APPEND HEADER "};\n\n")

    # 路由路径
    set(ROUTE_PATH "/${FILE_NAME}")

    # 收集资源条目
    string(APPEND RESOURCE_ENTRIES
        "    {std::string_view{\"${ROUTE_PATH}\"}, "
        "std::string_view{reinterpret_cast<const char*>(${DATA_VAR}), sizeof(${DATA_VAR})}},\n"
    )
endforeach()

# 写入 kResources 数组
string(APPEND HEADER "inline const Resource kResources[] = {\n")
string(APPEND HEADER "${RESOURCE_ENTRIES}")
string(APPEND HEADER "};\n\n")

# 写入资源计数
string(APPEND HEADER "inline const size_t kResourceCount = sizeof(kResources) / sizeof(kResources[0]);\n\n")
string(APPEND HEADER "} // namespace tianyan::webui::embedded\n")

file(WRITE "${OUTPUT_FILE}" "${HEADER}")
message(STATUS "Generated embedded resources: ${OUTPUT_FILE}")
