#!/usr/bin/env python3
"""
生成 webui_resources.h — 将 WebUI-Next/dist 中的文件编码为 C++ constexpr 字节数组。
比 CMake 的 string(SUBSTRING) 循环快 10-50x。
"""
import sys
import os
import glob

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} INPUT_DIR OUTPUT_FILE", file=sys.stderr)
        sys.exit(1)

    input_dir = sys.argv[1]
    output_file = sys.argv[2]

    # 收集资源文件
    resources = []
    for ext in ("*.html", "*.js", "*.css"):
        resources.extend(sorted(glob.glob(os.path.join(input_dir, ext))))

    if not resources:
        files = os.listdir(input_dir)
        print(f"FATAL: No .html / .js / .css files found in {input_dir}. Contents: {files}", file=sys.stderr)
        sys.exit(1)

    lines = []
    lines.append("// Auto-generated by embed_webui_resources.py — do not edit")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("#include <string_view>")
    lines.append("")
    lines.append("namespace tianyan::webui::embedded {")
    lines.append("")
    lines.append("struct Resource {")
    lines.append("    std::string_view path;")
    lines.append("    std::string_view data;")
    lines.append("};")
    lines.append("")

    resource_entries = []
    for file_path in resources:
        file_name = os.path.basename(file_path)
        data_name = "kData_" + "".join(c if c.isalnum() else "_" for c in file_name)

        with open(file_path, "rb") as f:
            data = f.read()

        if not data:
            print(f"WARNING: {file_path} is empty, skipping", file=sys.stderr)
            continue

        lines.append(f"// {file_name}")
        lines.append(f"inline constexpr unsigned char {data_name}[] __attribute__((used)) = {{")

        # 每行 20 字节
        for i in range(0, len(data), 20):
            chunk = data[i:i+20]
            hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
            lines.append(f"    {hex_bytes},")

        lines.append("};")
        lines.append("")

        route_path = f"/{file_name}"
        resource_entries.append(
            f'    {{std::string_view{{"{route_path}"}}, '
            f'std::string_view{{reinterpret_cast<const char*>({data_name}), sizeof({data_name})}}}},'
        )

    lines.append("inline const Resource kResources[] = {")
    lines.extend(resource_entries)
    lines.append("};")
    lines.append("")
    lines.append("inline const size_t kResourceCount = sizeof(kResources) / sizeof(kResources[0]);")
    lines.append("")
    lines.append("} // namespace tianyan::webui::embedded")
    lines.append("")

    with open(output_file, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated embedded resources: {output_file} ({len(data)} bytes in {len(resources)} file(s))")

if __name__ == "__main__":
    main()
